version: '3.9'
services:
  product:
    build: ./product
    container_name: product
    ports:
      - 8080:8080
  catalog:
    build: ./catalog
    container_name: catalog
    ports:
      - 8081:8081
    environment:
      PRODUCT_URL: http://product:8080
  checkout:
    build: ./checkout
    container_name: checkout
    ports:
      - 8082:8082
    environment:
      PRODUCT_URL: http://product:8080
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_HOST: rabbit
      RABBITMQ_DEFAULT_PORT: 5672
    depends_on:
      - rabbit
  order-checkout:
    build: ./order-checkout
    container_name: order-checkout
    ports:
      - 8083:8083
    environment:
      PRODUCT_URL: http://product:8080
      REDIS_HOST: redis:6379
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_HOST: rabbit
      RABBITMQ_DEFAULT_PORT: 5672
    depends_on:
      - rabbit
      - redis
  order-payment:
    build: ./order-payment
    container_name: order-payment
    ports:
      - 8085:8085
    environment:
      PRODUCT_URL: http://product:8080
      REDIS_HOST: redis:6379
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_HOST: rabbit
      RABBITMQ_DEFAULT_PORT: 5672
    depends_on:
      - rabbit
      - redis
  payment:
    build: ./payment
    container_name: payment
    ports:
      - 8084:8084
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_HOST: rabbit
      RABBITMQ_DEFAULT_PORT: 5672
    depends_on:
      - rabbit
  rabbit:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - "6379:6379"
